[package]
name = "bart"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.17", features = ["derive"] }
markdown = "1.0.0-alpha.20"
serde = {version="1.0.209", features=["derive"]}
toml = "0.8.19"
